# -*- coding: utf-8 -*-
"""Pandas DataFrame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PLj-watxt0b7sEDfnADDpUaFxHixR5eP

# Basic Data Structure

##### Info of Single Student
"""

student_sl = ['Ahmed Ali', 'Egypt, Giza', 24, 88.45]
student_sl

"""##### Info of Single Student with Names of Data"""

student_sd = {'name' : 'Ahmed Ali', 'address' : 'Egypt, Giza', 'age' : 24, 'gpa': 88.45}
student_sd

"""##### Info of Multiple Students"""

students_ml = [['Ahmed', 'Egypt, Giza', 24, 88.45],
            ['Hosam', 'Egypt, Sharm', 22, 78.12],
            ['Malek', 'Jordan, Amman', 21, 89.63]]
students_ml

"""##### Info of Multiple Students with Names of Data"""

students_mld = [{'name' : 'Ahmed', 'address' : 'Egypt, Giza', 'age' : 24, 'gpa': 88.45},
            {'name' : 'Hosam', 'address' : 'Egypt, Sharm', 'age' : 22, 'gpa': 78.12},
            {'name' : 'Malek', 'address' : 'Jordan, Amman', 'age' : 21, 'gpa': 89.63}]
students_mld

students_mdd = {'first': {'name' : 'Ahmed', 'address' : 'Egypt, Giza', 'age' : 24, 'gpa': 88.45},
            'second': {'name' : 'Hosam', 'address' : 'Egypt, Sharm', 'age' : 22, 'gpa': 78.12},
            'third': {'name' : 'Malek', 'address' : 'Jordan, Amman', 'age' : 21, 'gpa': 89.63}}
students_mdd

"""---

# Pandas DataFrame

##### Import library
"""

import pandas as pd

students_ml_df = pd.DataFrame(students_ml)
students_ml_df

students_mld_df = pd.DataFrame(students_mld)
students_mld_df

students_mdd_df = pd.DataFrame(students_mdd)
students_mdd_df

"""DataFrame (data, columns, index)

##### DataFrame with List
"""

data = [['Ahmed', 'Egypt, Giza', 24, 88.45],
            ['Hosam', 'Egypt, Sharm', 22, 78.12],
            ['Malek', 'Jordan, Amman', 21, 89.63]]

columns = ['name', 'address', 'age', 'gpa']

df = pd.DataFrame(data=data, columns=columns)
df

data = [['Ahmed', 'Egypt, Giza', 24, 88.45],
            ['Hosam', 'Egypt, Sharm', 22, 78.12],
            ['Malek', 'Jordan, Amman', 21, 89.63]]

columns = ['name', 'address', 'age', 'gpa']
index = ['01', '02', '03']

df = pd.DataFrame(data=data, columns=columns, index=index)
df

df.columns = ['nm', 'ad', 'ag', 'gpa']
df

df.index = df['nm']
df

"""##### DataFrame with Dict"""

data = [{'name' : 'Ahmed', 'address' : 'Egypt, Giza', 'age' : 24, 'gpa': 88.45},
            {'name' : 'Hosam', 'address' : 'Egypt, Sharm', 'age' : 22, 'gpa': 78.12},
            {'name' : 'Malek', 'address' : 'Jordan, Amman', 'age' : 21, 'gpa': 89.63}]

df = pd.DataFrame(data=data)
df

data = [{'name' : 'Ahmed', 'address' : 'Egypt, Giza', 'age' : 24},
            {'name' : 'Hosam', 'address' : 'Egypt, Sharm', 'gpa': 78.12},
            {'name' : 'Malek', 'age' : 21, 'gpa': 89.63}]

df = pd.DataFrame(data=data)
df

"""##### DataFrame Metadata"""

df.columns

df.index

df.attrs['src'] = 'my src'
df.attrs['about'] = 'info about students'
df.attrs['approx'] = 'very high'

df.attrs

df.describe()

df.info()

"""##### DataFrame - Get Row

loc[index]  
index can be int or str
"""

df.loc[0]

"""iloc[index]  
index is only int
"""

df.iloc[0]

"""loc[from:to]  
to is included
"""

df.loc[0:2]

"""iloc[from:to]  
to is excluded
"""

df.iloc[0:2]

df.iloc[0:1]

"""##### str index"""

data2 = [{'name' : 'Ali', 'address' : 'Egypt, Cairo', 'age' : 23},
            {'name' : 'Sarah', 'address' : 'Palestine, Gaza', 'gpa': 88.99},
            {'name' : 'Majd', 'age' : 22, 'gpa': 71.63}]

df2 = pd.DataFrame(data2)
df2

df2.index = ['first', 'second', 'third']
df2.index

df2.loc['first']

df2.loc['first': 'third']

"""##### DataFrame - Get Columns"""

df['age']

df[['name', 'age']]

df[['name', 'age']].loc[0]

"""##### DataFrame - Some Operations

merge 2 or more DataFrame's
"""

df3 = pd.concat([df, df2])
df3

"""apply math operation"""

df['gpa'] = df['gpa'] + 0.23
df

df['gpa'].min()

df['gpa'].max()

df.max()

df['gpa'].mean()

"""##### Resources

https://www.geeksforgeeks.org/python-pandas-dataframe/  
https://www.tutorialspoint.com/python_pandas/python_pandas_dataframe.htm  
https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python  
https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html  
https://www.learndatasci.com/tutorials/python-pandas-tutorial-complete-introduction-for-beginners/  
https://www.youtube.com/watch?v=UB3DE5Bgfx4
"""